### ISSUE TITLE
Privatekey

### ISSUE THREAD

**Issue by aliafshany** [jcreigh/pysurfshark#1]
hi 
thanks for this repo
would mind please telling me how to achieve private key?
i could run your script and the only thing that misses is Private key
best

**Comment by jcreigh** [comment]
Ah, the private key that goes on that line is the one you used when generating the public key the script asks for.

**Comment by aliafshany** [comment]
the thing is i don't have the privatekey at all.
the script asks for uesrname,password and a pubkey ( wich i don't have this one)

**Comment by jcreigh** [comment]
At least on Linux, you use the `wg` tool to generate both. The Wireguard site has info on all that stuff. The surfshark script kind of assumes some level of familiarity with setting up Wireguard in general. 

https://www.wireguard.com/quickstart/

**Comment by aliafshany** [comment]
thank you for sharing the link
best

**Comment by jcreigh** [comment]
No problem :)
